### ISSUE TITLE
Xiaomi 14T Pro not working

### ISSUE THREAD

**Issue by CrossiDev-Studio** [TheAirBlow/HyperSploit#15]
Your app is downgrading the settings app on Xiaomi 14T Pro, when I then try to enter Developer options, the app crashes

**Comment by TheAirBlow** [comment]
Check the pinned issue, there is another APK you could try. If it also doesn't work, you might be on your own to find and older compatibile version.

**Comment by CrossiDev-Studio** [comment]
Where is the pinned issue? I really cannot find it

**Comment by TheAirBlow** [comment]
#10
