### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Posapa** [TheAirBlow/HyperSploit#18]
when i install the downgraded settings app its just crashing when opening bluetooth and developer options please help
i know how to fix that but i want to root my device

**Comment by Posapa** [comment]
https://github.com/user-attachments/assets/70d1bd3e-dbd9-481f-be8e-41186207446b
Here is the video

**Comment by Posapa** [comment]
tried the #10 solution with the other app still didnt work

**Comment by Stromduster** [comment]
Same issue here.
