### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Posapa** [TheAirBlow/HyperSploit#19]
![image](https://github.com/user-attachments/assets/2e12baf2-6eac-490a-90bc-ed0442852080)

**Comment by TheAirBlow** [comment]
We can't bypass Xioami's restrictions.

**Comment by Posapa** [comment]
then what should i do

**Comment by TheAirBlow** [comment]
... nothing. get a phone that doesn't have restrictions imposed by xiaomi on it, or a different brand altogether.
