### ISSUE TITLE
Error 30003: The system is being upgraded. Please try again later.

### ISSUE THREAD

**Issue by bakaemon** [TheAirBlow/HyperSploit#2]
![image](https://github.com/TheAirBlow/HyperSploit/assets/69375806/c54db28e-571f-4f22-ba18-02b008c99c06)
Note that I am actually on HyperOS. I've chose to patched the Setting app.

**Comment by TheAirBlow** [comment]
Your phone/account was forced to go through Mi Community. There is no known bypass

**Comment by wefalltomorrow** [comment]
Is there any new method to bypass this?
