### ISSUE TITLE
Downgrade detected: Update version code 34 is older than current 35]

### ISSUE THREAD

**Issue by kiwirafe** [TheAirBlow/HyperSploit#20]
![image](https://github.com/user-attachments/assets/ecc3fd69-ab33-45c9-844a-6f06c668782b)

Unhandled exception caught, can't continue!
AdvancedSharpAdbClient.Exceptions.AdbException: Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 34 is older than current 35]

**Comment by TheAirBlow** [comment]
You're out of luck.
