### ISSUE TITLE
AdvancedSharpAdbClient.Exceptions.AdbException error

### ISSUE THREAD

**Issue by hichem19831** [TheAirBlow/HyperSploit#21]
![image](https://github.com/user-attachments/assets/0cfa92ff-c079-46cd-bde6-c20b04fc96f5)
Hi, a problem with xiaomi 14 ultra (android 15, hyperos) with this error AdvancedSharpAdbClient.Exceptions.AdbException

**Comment by TheAirBlow** [comment]
You're out of luck.
